config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  resources :articles do
    resources :comments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'articles#index'

  get "info_pages/about"
  get "info_pages/contact"
  post "info_pages/thank_you"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
        can :access, :ckeditor    # needed to access Ckeditor filebrowser
      else
        can :manage, User, id: user.id
        can [:create, :read], Comment
        can :read, Article
      end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  has_many :comments

  validates :title, presence: true
  validates :subject, presence: true
  validates :body, presence: true

  scope :updated_at_desc, -> {order(updated_at: :desc)}
  scope :updated_at_asc, -> {order(updated_at: :asc)}

  def self.search(search_term)
    Article.where("body LIKE ?", "%#{search_term}%")
  end

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :article

  validates :body, presence: true
  validates :user, presence: true
  validates :article, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, :alert => exception.message
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /articles
  # GET /articles.json
  def index
    if params[:q]
      search_term = params[:q]
      @articles = Article.search(search_term)
    else
      @articles = Article.order("updated_at DESC")
    end

  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @comments = @article.comments.order("created_at DESC")
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  def send_notice
    @user_mail = User.all
    @user_mail.each do |u|
      UserMailer.new_article(@user_mail).deliver_now
    end
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
        send_notice
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :subject, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
    redirect_to article_path(@article)
  end

  def destroy
  end

  private

    def comment_params
      params.require(:comment).permit(:user_id, :body)
    end

end

app/controllers/info_pages_controller.rb
class InfoPagesController < ApplicationController

  def thank_you
    @name = params[:name]
    @email = params[:email]
    @message = params[:message]
    UserMailer.contact_form(@email, @name, @message).deliver_now
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def create
    super
    if @user.persisted?
      UserMailer.welcome(@user).deliver_now
    end
  end

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :email_list)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :email_list)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/info_pages_helper.rb
module InfoPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<div class="article">
  <h3 class="article-title"> <%= link_to article.title, article %> </h3>
  <p class="date-posted"> <%= time_ago_in_words(article.updated_at) %> ago</p>
  <p class="article-body"> <%= article.body.truncate_words(100).html_safe %> </p>

  <% if signed_in? && current_user.admin? %>
    <%= link_to 'Edit', edit_article_path(article), :class => "btn btn-warning btn-sm" %>
    <%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-sm" %>
  <% end %>
  <hr>

</div> <!-- end article -->

app/views/articles/_article_list.html.erb
<!-- Listing of Articles for Sidebar -->

<h5 class="article-subject-list"> <%= article.subject %> </h5>
<h4 class="article-title-list"> <%= link_to article.title, article %> </h4>
<h5 class="article-updated-at"> <%= article.updated_at.to_formatted_s(:long) %> </h5>

<hr>

app/views/articles/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
        <div class="row">
            <hr>
            <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small></p>
            <p><%= comment.body %></p>
        </div>
    <% end %>
</div>

app/views/articles/_form.html.erb
<div class="enter-article-form container-fluid">
  <%= form_for(article) do |f| %>
    <% if article.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

        <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  <div class="form-fields col-sm-8 col-sm-offset-2">
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="field">
      <%= f.label :subject %>
      <%= f.text_field :subject, class: "form-control" %>
    </div>

    <div class="field">
      <%= f.label :body %>
      <%= f.cktext_area :body, class: "form-control" %>
    </div>

    <div class="actions">
      <%= f.submit class: "btn btn-success" %>
      <%= link_to 'Cancel Article', @article, :class => "btn btn-danger cancel-edit-btn" %>
      <%= link_to 'Back to All Articles', articles_path, :class => "btn btn-primary back-to-all-btn" %>
    </div>

  </div> <!-- end form-fields -->
  <% end %>
</div>

app/views/articles/_new_comment.html.erb
<% if signed_in? %>
  <h4>Add a comment:</h4>
  <%= form_for([@article, @article.comments.build]) do |f| %>
    <p>
      <%= f.label :body, "Comments" %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit "Submit" %>
    </p>
  <% end %>
<% end %>

app/views/articles/edit.html.erb
<div class="edit-page container-fluid">

  <h1>Editing Article</h1>

  <%= render 'form', article: @article %>

</div>

app/views/articles/index.html.erb
<div class="articles-index-page container-fluid col-sm-11">

  <div class="articles-main-page col-sm-12">
    <div class="articles-blog-blurb col-sm-9">
      <h1> Kath's Blog </h1>
        <% if signed_in? && current_user.admin? %>
          <%= link_to 'New Post', new_article_path, :class => "btn btn-success btn-lg" %>
        <% end %>

      <div class="articles col-sm-12">
        <%= render @articles %>
      </div> <!-- end articles -->
    </div> <!-- end articles-blog-blurb -->

    <div class="sidebar-articles-listing col-sm-3">
      <h4> This will be a blurb about the blog.  This is my blog I hope you like it.  I'm writing it because I want to share stuff.  I think this blurb should be short and sweet. </h4>

      <p class="btn btn-default"> <%= link_to('Sign Up for email updates', new_user_session_path) %> </p>

      <h3> Article listing </h3>

      <div class="search-box">
        <%= form_tag("/articles", method: "get") do %>
          <%= label_tag(:q, "Search for:", class: "search-label") %>
          <%= text_field_tag(:q, params[:q]) %>
          <%= submit_tag("Go", class: "btn btn-default search-button") %>
        <% end %>
      </div> <!-- end search-box -->

      <% @articles.each do |article| %>
          <%= render partial: "article_list", locals: {article: article} %>
      <% end %>
    </div> <!-- end sidebar-articles-listing -->
  </div> <!-- end articles-index-page -->
</div>

app/views/articles/new.html.erb
<div class="new-post-page container-fluid">

  <h1>New Article</h1>

  <%= render 'form', article: @article %>

</div>

app/views/articles/show.html.erb
<div class="show-article-page col-sm-10 col-sm-offset-1 container-fluid">

  <% if signed_in? && current_user.admin? %>
    <%= link_to 'Edit article', edit_article_path(@article), :class => "btn btn-warning" %>
    <%= link_to 'Delete article', @article, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
  <% end %>
  <%= link_to 'Back to All articles', articles_path, :class => "btn btn-primary back-to-all-btn" %>

  <div class="show-article col-sm-10 col-sm-offset-1">
    <h3 class="article-title"> <%= @article.title %> </h3>
    <p class="date-posted"> <%= @article.created_at %> </p>
    <p class="article-body"> <%= @article.body.html_safe %> </p>

    <%= render 'new_comment' %>

    <%= render 'comments' %>

  </div> <!-- end show-article-page -->

</div>

app/views/info_pages/about.html.erb
<div class="about-page col-sm-10 col-sm-offset-1 container-fluid">

<h1> This is the About page </h1>

</div> <!-- end about-page -->

app/views/info_pages/contact.html.erb
<div class="container-fluid col-sm-10 col-sm-offset-1 contact-page">
  <div class="col-md-12">
    <p> Kath's Logo or Header here </p>
  </div>

  <h1> Questions or comments for Kath?</h1>

  <h2> Fill out the form below or email her at kathblog@email.com </h2>

  <div class="contact-form col-sm-6 col-sm-offset-3">

    <%= flash[:notice] %>

    <%= form_tag("/info_pages/thank_you") do %>
        <div class="form-group">
          <%= label_tag :name, "Name", class: "contact-labels" %>
          <%= text_field_tag :name, nil, class: "form-control", placeholder: "Please Enter Your Name", required: "required" %>
        </div> <!-- end form-group -->

        <div class="form-group">
          <%= label_tag :email, "Email Address", class: "contact-labels" %>
          <%= text_field_tag :email, nil, class: "form-control", placeholder: "Please Enter Your Email", required: "required" %>
        </div> <!-- end form-group -->

        <div class="form-group">
          <%= label_tag :message, "Message", class: "contact-labels" %>
          <%= text_area_tag :message, nil, class: "form-control", placeholder: "Please Enter Your Message", required: "required" %>
        </div> <!-- end form-group -->
      <%= submit_tag "Send", class: "btn btn-default submit-button" %>
    <% end %>

  </div> <!-- end contact form -->

</div> <!-- end container-fluid -->

app/views/info_pages/thank_you.html.erb
<div class="thank-you-page col-sm-10 col-sm-offset-1 container-fluid">
  <div class="col-md-12 yc-logo">
    <p> Kath's logo/header here </p>
  </div>

  <div class="thank-you-message">
      <h3> Thank you! We have recieved your message and will get back to you as soon as possible. </h3>
  </div> <!-- end thank-you-message -->

  <div class="show-back-links col-sm-12">
    <h4> <%= link_to 'Back to Articles', articles_path %> |
    <%= link_to 'Back to Contact', info_pages_contact_path %></h4>
  </div>

</div> <!-- end thank-you-page -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kath's Blog</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

  </head>

  <body>
    <nav class="navbar navbar-fixed-top nav-menu">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button> <!--end button navbar -->
          <div class="navbar-brand">
            <!-- Logo or Home icon goes here -->
          </div> <!--end navbar-brand-->
        </div> <!--end navbar-header -->
        <div class="collapse navbar-collapse">


          <ul class="nav nav-pills navbar-right">
            <li> <%= link_to "Home", articles_path %> </li>
            <li> <%= link_to "About", info_pages_about_path %> </li>
            <!-- <li> Link_to "Articles", need path here </li> -->
            <li> <%= link_to "Contact", info_pages_contact_path %> </li>
            <li>
            <% if user_signed_in? %>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            <% else %>
              <%= link_to('Login', new_user_session_path) %>
            <% end %>
            </li>
          </ul>

        </div> <!-- end collapse navbar-collapse" -->
      </div> <!-- end container-fluid -->
    </nav>

    <% if notice %>
      <p id="notice"><%= notice %></p>
    <% end %>

    <% if alert %>
        <h3 class="alert alert-danger" role="alert"> <%= alert %> </h3>
    <% end %>

    <%= yield %>

    <footer class="navbar-fixed-bottom">
      <div class="container-fluid sticky-footer">
        <p class="p-footer col-sm-2"> &copy 2017 Kath Daily </p>
        <!-- <ul class="nav col-sm-3">
          <li>
          <% if user_signed_in? %>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
          <% else %>
            <%= link_to('Admin Login', new_user_session_path) %>
          <% end %>
          </li>
        </ul> -->
      </div>
    </footer>

  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_registration_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>